GET http://localhost:5000/api/articles

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "1234567",
    "password": "1234567"
}

###
GET http://localhost:5000/api/articles/649467d05be2d73b5194aac5

###
POST http://localhost:5000/api/articles
Content-Type: application/json

{
    "title": "The Ultra Updated DOM article",
    "description": "New markdoan article you need to know",
    "markdown": "test"
}

###
DELETE http://localhost:5000/api/articles/649467d05be2d73b5194aac5

###
PATCH http://localhost:5000/api/articles/649465380bba181e0eed76bc
Content-Type: application/json

{
    "title": "Beautiful Sexy Updated DOM article"
}