GET http://localhost:5000/api/articles

###
GET http://localhost:5000/api/profile/details

###
DELETE http://localhost:5000/database

###
POST http://localhost:5000/api/profile/edit
Content-Type: application/json

{
    "bio": "Another test",
    "location": "Abuja",
    "image": "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "sixthuser6",
    "password": "sixthuser6"
}

###
GET http://localhost:5000/auth/logout

###
GET http://localhost:5000/api/articles/649467d05be2d73b5194aac5

###
POST http://localhost:5000/api/articles
Content-Type: application/json

{
    "title": "The Ultra Updated DOM article",
    "description": "New markdoan article you need to know",
    "markdown": "test"
}

###
DELETE http://localhost:5000/api/articles/649467d05be2d73b5194aac5

###
PATCH http://localhost:5000/api/articles/649465380bba181e0eed76bc
Content-Type: application/json

{
    "title": "Beautiful Sexy Updated DOM article"
}